# Notice: This template has only been tested 
# under Python27 + GAE standard environment
application: oauth2-assignment-cs496
runtime: python27
version: 1
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: oauth2.app

libraries:
- name: flask
  version: 0.12